travel/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from flask import g

from . import db

# a blueprint to manage authentication
bp = Blueprint('auth',__name__)




@bp.route('/register', methods = ['GET', 'POST'])  
def register():  
  #create the form
    form = RegisterForm()
    #this line is called when the form - POST
    if form.validate_on_submit():
      print('Register form submitted')
       
      #get username, password and email from the form
      fname = form.first_name.data
      lname = form.last_name.data
      phone = form.phone_num.data
      emailin = form.email.data
      pwd = form.password.data

          

    #   uname =form.username.data
    #   pwd = form.password.data
    #   email=form.email.data
    #   utype =form.usertype.data
      
      pwd_hash = generate_password_hash(pwd)
      #create a new user model object
      new_user = User(first_name=fname, last_name=lname, phone_num=phone, email=emailin, password_hash=pwd_hash)
      db.session.add(new_user)
      db.session.commit()
      flash("Registered user successfully")
      return redirect(url_for('auth.register'))
       
    return render_template('user.html', form=form, heading='Register', user=current_user)
    


@bp.route('/login', methods = ['GET', 'POST'])
def login():
  form = LoginForm()
  error=None
  if(form.validate_on_submit()):
    uemail = form.user_email.data
    password = form.password.data
    u1 = User.query.filter_by(email=uemail).first()
    
        #if there is no user with that name
    if u1 is None:
      error='Incorrect user email'
    #check the password - notice password hash function
    elif not check_password_hash(u1.password_hash, password): # takes the hash and password
      error='Incorrect password'
    if error is None:
    #all good, set the login_user
      login_user(u1)
      print("loged in")
      return redirect(url_for('main.index'))
    else:
      print(error)
      flash(error)
    #it comes here when it is a get method
  return render_template("user.html", form=form, heading='Login', user=current_user)


@bp.route('/logout/')
def logout():
  logout_user()
  
  return redirect(url_for("main.index"))

travel/views.py
from flask import Blueprint, render_template, request, redirect,url_for
from flask_login import login_required, current_user

from .models import Event, User

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    events = Event.query.all()
    user = User.query.first()
    return render_template('index.html', events=events, user=current_user)

@mainbp.route('/update/<user_id>', methods = ['GET', 'POST'])
def update(user_id):
  print('Method type: ', request.method)
  user = User.query.filter_by(id=user_id).first()
  events = Event.query.filter_by(created_by=user_id).all()
  return render_template('events/my_events.html', user=current_user, events=events)

@mainbp.route('/search')
def search():
    if request.args['search']:
        print(request.args['search'])
        ev = "%" + request.args['search'] + '%'
        events = Event.query.filter(Event.description.like(ev)).all()
        return render_template('index.html', events=events, user=current_user)
    else:
        return redirect(url_for('main.index', user=current_user))

travel/templates/base.html
<html>

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>My Events</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
      <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/styles.css') }}">

</head>

<body>
   <!-- Header -->
   <header class="sticky-top">

      <!-- Navbar -->

      <nav class="navbar navbar-expand-sm navbar-dark">
         <div class="container-fluid">
            <a class="navbar-brand" href="/">Noisy Nights</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <div id="nav-level">
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           My Events
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                           <li><a class="dropdown-item" href="/events/create">Create Events</a></li>
                           <li><a class="dropdown-item" href="{{url_for('main.update', user_id=current_user.id)}}">Update Events</a></li>
                        </ul>
                     </li>
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Account
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                           {% if user.is_authenticated %}
                              <li><a class="dropdown-item" href="">My Account</a></li>
                              <li><a class="dropdown-item" href="/logout">Logout</a></li>
                           {% else %}
                              <li><a class="dropdown-item" href="/login">Login</a></li>
                              <li><a class="dropdown-item" href="/register">Register</a></li>
                           {% endif %}
                        </ul>
                     </li>
                  </div>
               </ul>
               
               
               <form class="d-flex" role="search">
                  
                  <input class="form-control me-2" type="search" placeholder="Search Events" aria-label="Search">
                  <button class="btn btn-primary" type="submit">Search</button>
               </form>
            </div>
         </div>
      </nav>

    {% block header %}
    {% endblock %}

   </header>
      
   {% block content %}
   {% endblock %}
   
    <footer class="footer">
        <div class="text-center py-2 bg-dark">
            <span class="text-light">Copyright &copy; 2021</span>
        </div>
    </footer> 
   
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
         integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
         crossorigin="anonymous"></script>
   </body>

</html>

travel/templates/base_no_py.html
<html>

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>My Events</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
      <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/styles.css') }}">

</head>

<body>
   <!-- Header -->
   <header class="sticky-top">

      <!-- Navbar -->

      <nav class="navbar navbar-expand-sm navbar-dark">
         <div class="container-fluid">
            <a class="navbar-brand" href="/">Noisy Nights</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               <div id="nav-level">
                  <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                     My Events
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                     <li><a class="dropdown-item" href="/events/create">Create Events</a></li>
                     <li><a class="dropdown-item" href="{{url_for('main.update', user_id=current_user.id)}}">Update Events</a></li>
                  </ul>
                  </li>
               </div>
            </ul>
            <form class="d-flex" role="search">
               <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
               </a>
               <ul class="dropdown-menu dropdown-menu-dark">
                  
                     <li><a class="dropdown-item" href="">My Account</a></li>
                     <li><a class="dropdown-item" href="/logout">Logout</a></li>
                  
                     <li><a class="dropdown-item" href="/login">Login</a></li>
                     <li><a class="dropdown-item" href="/register">Register</a></li>
                  
               </ul>
               <input class="form-control me-2" type="search" placeholder="Search Events" aria-label="Search">
               <button class="btn btn-primary" type="submit">Search</button>
            </form>
            </div>
         </div>
      </nav>

    {% block header %}
    {% endblock %}

   </header>
      
   {% block content %}
   {% endblock %}
   
    <footer class="footer">
        <div class="text-center py-2 bg-dark">
            <span class="text-light">Copyright &copy; 2021</span>
        </div>
    </footer> 
   
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
         integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
         crossorigin="anonymous"></script>
   </body>

</html>

travel/templates/index.html
{% extends 'base.html' %}

{% block content %}   
<div>

   <!-- CAROUSEL -->
   
   <div id="carouselExampleDark" class="carousel carousel-light slide" data-bs-ride="carousel">
      <div class="carousel-inner">

         <div class="carousel-item active" data-bs-interval="10000">
            <div style="height: 300px">
               <img src="static/image/event.png" id="create_img">
            </div>
            <div class="carousel-caption d-none d-sm-block">
               <h1><b>Featured events</b></h1>
            </div>
         </div>
         {% for event in events %}
            <div class="carousel-item" data-bs-interval="5000">
               <div style="height: 300px">
                  <img src="{{event.img_link1}}" id="create_img">
               </div>
               <div class="carousel-caption d-none d-sm-block">
                  <h3><b>{{event.name}}</b></h3>
                  <p>{{event.description}}</p>
               </div>
            </div>
         {% endfor %}
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
         <span class="carousel-control-prev-icon" aria-hidden="true"></span>
         <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
         <span class="carousel-control-next-icon" aria-hidden="true"></span>
         <span class="visually-hidden">Next</span>
      </button>
   </div>

   <!-- NAV BAR 2 -->

   <div>
      <nav class="navbar navbar-expand-sm navbar-dark">
         <div class="container-fluid">
         <a class="navbar-brand" href="#">All events</a>
         <ul class="navbar-nav mb-lg-0">
            <li class="nav-item">
               <button class="btn me-2 btn-primary" type="submit">Load All Events</button>
            </li>
            <li class="nav-item">
               <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">Select Category</button>
            </li>
         </ul>
         </div>
      </nav>
   </div>

   <!-- CATEGORY OFFCANVAS -->

   <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
      <div class="offcanvas-header">
         <h5 class="offcanvas-title" id="offcanvasDarkLabel">Categories</h5>
         <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body" id="offcanvas">
         <ul>
         <li class="nav-item">
            <a class="nav-link" href="/events/pop">Pop</a>
         </li>
         <li class="nav-item">
            <a class="nav-link" href="/events/rock">Rock</a>
         </li>
         <li class="nav-item">
            <a class="nav-link" href="/events/hiphop">Hip Hop</a>
         </li>
         <li class="nav-item">
            <a class="nav-link" href="/events/country">Country</a>
         </li>
         <li class="nav-item">
            <a class="nav-link" href="/events/indie">Indie</a>
         </li>
         <li class="nav-item">
            <a class="nav-link" href="/events/jazz">Jazz</a>
         </li>
         </ul>
      </div>
   </div>
</div>

<!-- EVENT CARDS -->

<div class="card-group">
      {% for event in events %}
      <article class="col">
         <div id="card" class="card" style="width: 18rem; background-color: rgb(33, 33, 33)">
            <img class="card-img-top"
               src={{event.img_link1}} alt="event picture" id="create_img">
            <div class="card-body">
               <h5 class="card-title">{{event.name}}</h5>
               <p class="card-text">{{event.description}}</p>
            </div>
            <div class="card-footer"><a href = "{{url_for('event.show', event_id=event.event_id)}}" class ="btn btn-danger"> View Details </a></div>
         </div>
      </article>
      {% endfor %}
</div>

{% endblock %}

travel/templates/messages.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Messages {% endblock %}</h1>
    <h2>{{ message }}</h2>
{% endblock %}

travel/templates/user.html
{% extends "base.html" %}
{% import "bootstrap4/form.html" as wtf %}

{% block content %}

<div class="container-fluid">
<div class="page-header">
    <h4>{{heading}}</h4>
</div>

<!-- flashes any messages to the user -->
{% with messages = get_flashed_messages() %}
{% if messages %} <!-- check if there are any messages -->
  <div class="container-fluid">
    <div class="row mt-3 mb-3">
      <div class="col-md-12">
      {% for message in messages %} <!--loop through the messages-->
        <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}
{% endwith %}

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6 ml-5">
{{wtf.render_form(form)}}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4 mb-5 ml-5">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endif %}
<!-- When you have register form, then do show the user a link to login -->
{% if heading|lower =='register' %}
<div class="col-md-4 mb-5 ml-5">
    <p>Made an account? <a href="{{ url_for('auth.login') }}">Click here to login</a>.</p>
</div>
{% endif %}
</div>
{% endblock %}